# Generated by Django 5.1 on 2024-09-14 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Permissions',
            new_name='Permis',
        ),
    ]
