# Generated by Django 5.1 on 2024-10-01 02:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0007_auditoria_empleado_rol_delete_roles_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asignacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auditoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_app.auditoria')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_app.empleado')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_app.rol')),
            ],
            options={
                'unique_together': {('auditoria', 'empleado')},
            },
        ),
    ]
