# Generated by Django 5.1 on 2024-10-08 21:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0008_asignacion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auditoria',
            old_name='empleados',
            new_name='recursos',
        ),
        migrations.RenameModel(
            old_name='Empleado',
            new_name='Recursos',
        ),
        migrations.RenameModel(
            old_name='Rol',
            new_name='Roles',
        ),
        migrations.CreateModel(
            name='AuditoriaRolesRecursos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auditoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_app.auditoria')),
                ('recurso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_app.recursos')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_app.roles')),
            ],
            options={
                'unique_together': {('auditoria', 'recurso')},
            },
        ),
        migrations.DeleteModel(
            name='Asignacion',
        ),
    ]
