# Generated by Django 5.1 on 2024-10-08 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0009_rename_empleados_auditoria_recursos_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_team', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=255)),
                ('integrantes', models.CharField(max_length=100)),
                ('recursos', models.ManyToManyField(related_name='teams', to='base_app.recursos')),
            ],
        ),
        migrations.CreateModel(
            name='Areas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=255)),
                ('team', models.ManyToManyField(related_name='area', to='base_app.teams')),
            ],
        ),
    ]
